packages:
  - "apps/*"
  - "packages/*"
  - "packages/core/tests"
  - "packages/core/e2e"
  - "packages/core/e2e/examples/*"
  - "packages/autotool/examples/*"
  - "packages/edge/e2e/*"
  - "examples/"
  - "examples/*"
