export const IndexStructType = {
  NODE: "node",
  TREE: "tree",
  LIST: "list",
  KEYWORD_TABLE: "keyword_table",
  DICT: "dict",
  SIMPLE_DICT: "simple_dict",
  WEAVIATE: "weaviate",
  PINECONE: "pinecone",
  QDRANT: "qdrant",
  LANCEDB: "lancedb",
  MILVUS: "milvus",
  CHROMA: "chroma",
  MYSCALE: "myscale",
  CLICKHOUSE: "clickhouse",
  VECTOR_STORE: "vector_store",
  OPENSEARCH: "opensearch",
  DASHVECTOR: "dashvector",
  CHATGPT_RETRIEVAL_PLUGIN: "chatgpt_retrieval_plugin",
  DEEPLAKE: "deeplake",
  EPSILLA: "epsilla",
  MULTIMODAL_VECTOR_STORE: "multimodal",
  SQL: "sql",
  KG: "kg",
  SIMPLE_KG: "simple_kg",
  SIMPLE_LPG: "simple_lpg",
  NEBULAGRAPH: "nebulagraph",
  FALKORDB: "falkordb",
  EMPTY: "empty",
  COMPOSITE: "composite",
  PANDAS: "pandas",
  DOCUMENT_SUMMARY: "document_summary",
  VECTARA: "vectara",
  ZILLIZ_CLOUD_PIPELINE: "zilliz_cloud_pipeline",
  POSTGRESML: "postgresml",
} as const;

export type IndexStructType =
  (typeof IndexStructType)[keyof typeof IndexStructType];
