export { DEFAULT_PERSIST_PATH, DEFAULT_PERSIST_DIR, DEFAULT_PERSIST_FNAME} from './types'

export { DEFAULT_METADATA_COLLECTION_SUFFIX, DEFAULT_COLLECTION_DATA_SUFFIX, DEFAULT_NAMESPACE, DEFAULT_REF_DOC_COLLECTION_SUFFIX} from './kv-document-store'