name: TypeScript Compilation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install pnpm
      run: npm install -g pnpm@7.15.0

    - name: Install dependencies
      run: pnpm install

    - name: Run test
      run: pnpm run test

    - name: Run lint
      run: pnpm run lint